# Change these first
owner: zeitlabs # Your GitHub username
repo: uptime-checker # Your Github repository name

# Add your sites here
sites:
  - name: school
    url: https://sch.bikou.in
  - name: att
    url: https://att.bikou.in
  - name: dcsd
    url: https://dcsd.bikou.in
  - name: tsa
    url: https://tsa-dev.bikou.in
  - name: ZEIT X LINCK
    url: https://www.zeitxlinck.com

expectedStatusCodes:
  - 200
  - 401

assignees:
  - name: eit

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: up.zeit.cx
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Uptime monitoring."
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
